javascript:(function() {
  var quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
    "The way to get started is to quit talking and begin doing. -Walt Disney",
    "Your time is limited, don't waste it living someone else's life. -Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. -Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron",
    "Life is what happens when you're busy making other plans. -John Lennon",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. -Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. -Franklin D. Roosevelt",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. -Robert Louis Stevenson",
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. -Steve Jobs",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. -Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. -Helen Keller",
    "It is during our darkest moments that we must focus to see the light. -Aristotle Onassis",
    "Whoever is happy will make others happy too. -Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
    "I have learned over the years that when one's mind is made up, this diminishes fear. -Rosa Parks",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean",
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "Too many of us are not living our dreams because we are living our fears. -Les Brown",
    "Do what you can, with what you have, where you are. -Theodore Roosevelt",
    "Everything you've ever wanted is on the other side of fear. -George Addair",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. -Winston Churchill",
        "Don't Let Yesterday Take Up Too Much Of Today. - Will Rogers",
    "You Are Never Too Old To Set Another Goal Or To Dream A New Dream. - C.S. Lewis",
    "Believe You Can And You're Halfway There. - Theodore Roosevelt",
    "I Can't Change The Direction Of The Wind, But I Can Adjust My Sails To Always Reach My Destination. - Jimmy Dean",
    "To Succeed In Life, You Need Two Things: Ignorance And Confidence. - Mark Twain",
    "You Are Never Too Old To Set Another Goal Or To Dream A New Dream. - Les Brown",
    "Success Is Not Final, Failure Is Not Fatal: It Is The Courage To Continue That Counts. - Winston Churchill",
    "The Only Limit To Our Realization Of Tomorrow Will Be Our Doubts Of Today. - Franklin D. Roosevelt",
    "What You Get By Achieving Your Goals Is Not As Important As What You Become By Achieving Your Goals. - Zig Ziglar",
    "Believe In Yourself And All That You Are. Know That There Is Something Inside You That Is Greater Than Any Obstacle. - Christian D. Larson",
    "I Have Not Failed. I've Just Found 10,000 Ways That Won't Work. - Thomas Edison",
    "The Future Belongs To Those Who Believe In The Beauty Of Their Dreams. - Eleanor Roosevelt",
    "It's Not Whether You Get Knocked Down, It's Whether You Get Up. - Vince Lombardi",
    "You Can't Build A Reputation On What You Are Going To Do. - Henry Ford",
    "If You Are Working On Something That You Really Care About, You Don't Have To Be Pushed. The Vision Pulls You. - Steve Jobs",
    "The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty. - Winston Churchill",
    "You Are Braver Than You Believe, Stronger Than You Seem, And Smarter Than You Think. - A.A. Milne",
    "If You Are Not Willing To Risk The Usual, You Will Have To Settle For The Ordinary. - Jim Rohn",
    "We May Encounter Many Defeats But We Must Not Be Defeated. - Maya Angelou",
    "Knowing Is Not Enough; We Must Apply. Wishing Is Not Enough; We Must Do. - Johann Wolfgang Von Goethe",
    "The Man Who Has Confidence In Himself Gains The Confidence Of Others. - Hasidic Proverb",
    "If You Are Not A Risk Taker, You Should Get The Hell Out Of Business. - Ray Kroc",
    "There Are No Limits To What You Can Accomplish, Except The Limits You Place On Your Own Thinking. - Brian Tracy",
    "We Generate Fears While We Sit. We Overcome Them By Action. - Dr. Henry Link",
    "Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing. - Helen Keller",
    "The Only Way To Do Great Work Is To Love What You Do. If You Haven't Found It Yet, Keep Looking. Don't Settle. - Steve Jobs",
    "You Don't Have To Be Great To Start, But You Have To Start To Be Great. - Zig Ziglar",
    "Success Is Walking From Failure To Failure With No Loss Of Enthusiasm. - Winston Churchill",
    "The Only Person You Are Destined To Become Is The Person You Decide To Be. - Ralph Waldo Emerson",
    "We May Encounter Many Defeats But We Must Not Be Defeated. - Maya Angelou",
        "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. -Steve Jobs",
    "Don't let yesterday take up too much of today. -Will Rogers",
    "You miss 100% of the shots you don't take. -Wayne Gretzky",
    "The best way to predict the future is to create it. -Peter Drucker",
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "Strive not to be a success, but rather to be of value. -Albert Einstein",
    "I have not failed. I've just found 10,000 ways that won't work. -Thomas Edison",
    "You can't build a reputation on what you are going to do. -Henry Ford",
    "It's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
    "You can never cross the ocean until you have the courage to lose sight of the shore. -Christopher Columbus",
    "The two most important days in your life are the day you are born and the day you find out why. -Mark Twain",
    "I would rather die of passion than of boredom. -Vincent van Gogh",
    "The journey of a thousand miles begins with one step. -Lao Tzu",
    "I attribute my success to this: I never gave or took any excuse. -Florence Nightingale",
    "I am not a product of my circumstances. I am a product of my decisions. -Stephen Covey",
    "If you want to live a happy life, tie it to a goal, not to people or things. -Albert Einstein",
    "Either you run the day, or the day runs you. -Jim Rohn",
    "Your time is limited, don't waste it living someone else's life. -Steve Jobs",
    "I didn't fail the test. I just found 100 ways to do it wrong. -Benjamin Franklin",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
    "Success is not how high you have climbed, but how you make a positive difference to the world. -Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. -Ralph Waldo Emerson",
    "Be the change that you wish to see in the world. -Mahatma Gandhi",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. -Martin Luther King Jr.",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "Change your thoughts and you change your world. -Norman Vincent Peale",
    "Life is 10% what happens to us and 90% how we react to it. -Charles R. Swindoll",
    "It does not matter how slowly you go as long as you do not stop. -Confucius",
    "The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt",
    ];
  
    var index = Math.floor(Math.random() * quotes.length);
  alert(quotes[index]);
})();

